# Generated by Django 4.1.2 on 2022-10-25 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('extra_phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('web_site', models.URLField(null=True)),
                ('uz_address', models.CharField(max_length=200)),
                ('en_address', models.CharField(max_length=200)),
                ('ru_address', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutoDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz_name', models.CharField(max_length=200)),
                ('ru_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('post_view', models.ImageField(blank=True, default=0, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='backgroundImage/')),
            ],
        ),
        migrations.CreateModel(
            name='BlogsBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to='posts/')),
                ('uz_title', models.CharField(max_length=200)),
                ('ru_title', models.CharField(max_length=200)),
                ('en_title', models.CharField(max_length=200)),
                ('uz_description', models.CharField(max_length=100)),
                ('ru_description', models.CharField(max_length=100)),
                ('en_description', models.CharField(max_length=100)),
                ('uz_post', models.TextField()),
                ('ru_post', models.TextField()),
                ('en_post', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('post_view', models.IntegerField(blank=True, default=0, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NavbarName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz_name', models.CharField(max_length=200)),
                ('ru_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('post_view', models.ImageField(blank=True, default=0, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AboutAreas',
            fields=[
                ('blogsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.blogsbase')),
            ],
            bases=('main.blogsbase',),
        ),
        migrations.CreateModel(
            name='ArtAndMemorials',
            fields=[
                ('blogsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.blogsbase')),
            ],
            bases=('main.blogsbase',),
        ),
        migrations.CreateModel(
            name='CafeAndResutaran',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.address')),
            ],
            bases=('main.address',),
        ),
        migrations.CreateModel(
            name='HeaderSliders',
            fields=[
                ('blogsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.blogsbase')),
            ],
            bases=('main.blogsbase',),
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.address')),
                ('hotel_img', models.ImageField(default='default/hotel.jpg', upload_to='hotels_images/')),
                ('hotel_description_uz', models.TextField()),
                ('hotel_description_ru', models.TextField()),
                ('hotel_description_en', models.TextField()),
            ],
            bases=('main.address',),
        ),
        migrations.CreateModel(
            name='Masjid',
            fields=[
                ('blogsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.blogsbase')),
            ],
            bases=('main.blogsbase',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('blogsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.blogsbase')),
            ],
            bases=('main.blogsbase',),
        ),
        migrations.CreateModel(
            name='PhotoArxiv',
            fields=[
                ('autodate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autodate')),
                ('photo', models.ImageField(upload_to='photo_arxiv/')),
            ],
            bases=('main.autodate',),
        ),
        migrations.CreateModel(
            name='RelaxPlaces',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.address')),
                ('place_img', models.ImageField(default='default/hotel.jpg', upload_to='hotels_images/')),
                ('place_description_uz', models.TextField()),
                ('place_description_ru', models.TextField()),
                ('place_description_en', models.TextField()),
            ],
            bases=('main.address',),
        ),
        migrations.CreateModel(
            name='Shrines',
            fields=[
                ('blogsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.blogsbase')),
            ],
            bases=('main.blogsbase',),
        ),
        migrations.CreateModel(
            name='WebSiteName',
            fields=[
                ('autodate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autodate')),
            ],
            bases=('main.autodate',),
        ),
        migrations.CreateModel(
            name='PlacesName',
            fields=[
                ('autodate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autodate')),
                ('navbarname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.navbarname')),
            ],
            bases=('main.autodate',),
        ),
        migrations.CreateModel(
            name='NavbarAreas',
            fields=[
                ('autodate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autodate')),
                ('status', models.CharField(choices=[('tuman', 'tuman'), ('shaxar', 'shaxar'), ('district', 'district'), ('city', 'city')], max_length=200)),
                ('navbarname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.navbarname')),
            ],
            bases=('main.autodate',),
        ),
    ]
