# Generated by Django 4.1.2 on 2022-11-22 16:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_backgroundimagefornews_bg_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='bg_img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[5000, 5000], upload_to='backgroundImage/'),
        ),
    ]
