# Generated by Django 4.1.2 on 2022-10-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_shrines'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitename',
            name='logo',
            field=models.ImageField(default='logo.png', upload_to='logo/'),
        ),
    ]
