# Generated by Django 4.1.2 on 2022-10-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_autodate_post_view_alter_navbarname_post_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitename',
            name='logo',
            field=models.ImageField(default='default/logo.png', upload_to='logo/'),
        ),
    ]
