# Generated by Django 4.1.2 on 2022-10-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_websitename_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarareas',
            name='status',
            field=models.CharField(choices=[('tuman', 'tuman'), ('shaxar', 'shaxar'), ('district', 'district'), ('city', 'city'), ('город', 'город'), ('район', 'район')], max_length=200),
        ),
    ]
