# Generated by Django 4.1.2 on 2022-10-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_navbarareas_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavbarAreas',
        ),
    ]
