# Generated by Django 4.1.2 on 2022-10-26 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_navbarareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarItems',
            fields=[
                ('autodate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autodate')),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navbarname')),
            ],
            bases=('main.autodate',),
        ),
        migrations.CreateModel(
            name='NavbarAreasUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz_name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('tuman', 'tuman'), ('shaxar', 'shaxar')], max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navbarname')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarAreasRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('город', 'город'), ('район', 'район')], max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navbarname')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarAreasEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('city', 'city'), ('district', 'district')], max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navbarname')),
            ],
        ),
    ]
