# Generated by Django 4.1.2 on 2022-10-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_navbaritems_navbarareasuz_navbarareasru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImageForAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForAreas/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForRelax/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForCafe/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForHotel/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForMasjid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForMasjid/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForNews/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForPhotos/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForRelax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForRelax/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForShrines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForShrines/')),
            ],
        ),
    ]
