# Generated by Django 4.1.2 on 2022-10-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_backgroundimageforareas_backgroundimageforart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodate',
            name='en_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='autodate',
            name='ru_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogsbase',
            name='en_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogsbase',
            name='en_post',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsbase',
            name='en_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogsbase',
            name='ru_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogsbase',
            name='ru_post',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsbase',
            name='ru_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='navbarname',
            name='en_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='navbarname',
            name='ru_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
